language = "C"

[parse]
parse_deps = true
include = ["libxml2"]
clean = false

[export]
include = [
    "xmlDoc",
    "xmlParserCtxt",
    "xmlElementType",
    "xmlAttributeType",
    "xmlNode",
    "xmlNs",
    "xmlAttr",
]
